"""Regenerate the three ``docs/latex/figures/gyro/*.tex`` table fragments used
by the "Gyroscope orientation reconstruction" section (\\S15) of ``main.tex``.

Inputs (all produced by the reproduction pipeline, see
``scripts/reproduce_gyro_report.sh``):

* ``--comparison`` --- ``figures/reconstruct_az/comparison_metrics.json`` from
  ``scripts/reconstruction_comparison_report.py --kind all`` (holds the full-set
  ``none`` vs. ``Mahony`` prediction + segmentation metrics).
* ``--none-test`` / ``--mahony-test`` --- ``metrics.json`` from a held-out
  ``evaluateOnData --kind test`` run without / with ``--reconstruct Mahony``
  (the calibrated-CI comparison, Table 36).

Writes ``pred_improvement.tex``, ``seg_improvement.tex`` and
``mahony_calibrated.tex`` --- the same ``resizebox``+``booktabs`` house style the
rest of the paper uses. Bold marks the Mahony cell whenever it beats the
baseline (lower MAE/RMSE/CI/error, higher coverage/within-floor/F1).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _b(s: str, bold: bool) -> str:
    return f"\\textbf{{{s}}}" if bold else s


def _pct(x: float) -> str:
    return f"{x * 100:.1f}\\%"


def _f(x: float, nd: int) -> str:
    return f"{x:.{nd}f}"


def write_pred_improvement(comp: dict, out: Path) -> None:
    p = comp["prediction"]
    rows = []
    for algo_label, algo in (("ZUPT", "zupt"), ("Trapezoid", "trapezoid")):
        n = p[f"none/{algo}"]
        m = p[f"Mahony/{algo}"]
        mae = _b(_f(m["clean_mae"], 3), True)
        rmse = _b(_f(m["clean_rmse"], 3), True)
        cov = _b(_pct(m["clean_coverage_90"]), m["clean_coverage_90"] > n["clean_coverage_90"])
        wf = _b(_pct(m["clean_frac_within_1_5m"]), m["clean_frac_within_1_5m"] > n["clean_frac_within_1_5m"])
        ci = _b(_f(m["clean_median_ci"], 3), m["clean_median_ci"] < n["clean_median_ci"])
        rows.append(
            f"\\multirow{{2}}{{*}}{{{algo_label}}} & none (baseline) & "
            f"{_f(n['clean_mae'], 3)} & {_f(n['clean_rmse'], 3)} & "
            f"{_pct(n['clean_coverage_90'])} & {_pct(n['clean_frac_within_1_5m'])} & "
            f"{_f(n['clean_median_ci'], 3)} \\\\"
        )
        rows.append(
            f"                      & \\textbf{{Mahony}} & {mae} & {rmse} & {cov} & {wf} & {ci} \\\\"
        )
    body = "\n\\midrule\n".join("\n".join(rows[i:i + 2]) for i in range(0, len(rows), 2))
    out.write_text(
        "% Auto-generated by scripts/reproduce_gyro_report_tables.py from\n"
        "% figures/reconstruct_az/comparison_metrics.json (--kind all).\n"
        "\\resizebox{\\textwidth}{!}{%\n"
        "\\begin{tabular}{llrrrrr}\n\\toprule\n"
        "Algorithm & Reconstruction & MAE (m) & RMSE (m) & Cov@90 & "
        "$\\le 1.5$\\,m & med.\\ CI (m) \\\\\n\\midrule\n"
        f"{body}\n"
        "\\bottomrule\n\\end{tabular}%\n}\n"
    )


def write_seg_improvement(comp: dict, out: Path) -> None:
    n = comp["segmentation"]["none"]
    m = comp["segmentation"]["Mahony"]
    nt, ni = n["total"], n["iou"]
    mt, mi = m["total"], m["iou"]
    det = _b(str(mt["clean"]), mt["clean"] > nt["clean"])
    miss = _b(str(mt["missed"]), mt["missed"] < nt["missed"])
    fp = _b(str(mt["fp"]), mt["fp"] < nt["fp"])
    f1 = _b(_f(mt["f1_like"], 3), mt["f1_like"] > nt["f1_like"])
    iou = _b(_f(mi["iou_f1@0.5"], 3), mi["iou_f1@0.5"] > ni["iou_f1@0.5"])
    prec = _b(_f(mt["precision"], 3), mt["precision"] > nt["precision"])
    row_n = (
        f"none (baseline) & {nt['n_gt']} & {nt['clean']} & {nt['missed']} & "
        f"{nt['fp']} & {_f(nt['f1_like'], 3)} & {_f(ni['iou_f1@0.5'], 3)} & "
        f"{_f(nt['precision'], 3)} \\\\"
    )
    row_m = f"\\textbf{{Mahony}} & {mt['n_gt']} & {det} & {miss} & {fp} & {f1} & {iou} & {prec} \\\\"
    out.write_text(
        "% Auto-generated by scripts/reproduce_gyro_report_tables.py from\n"
        "% figures/reconstruct_az/comparison_metrics.json (--kind all).\n"
        "\\resizebox{\\textwidth}{!}{%\n"
        "\\begin{tabular}{lrrrrrrr}\n\\toprule\n"
        "Reconstruction & $n_{\\rm gt}$ & detected & missed & FP & $F1^\\ast$ & "
        "IoU-F1@0.5 & precision \\\\\n\\midrule\n"
        f"{row_n}\n{row_m}\n"
        "\\bottomrule\n\\end{tabular}%\n}\n"
    )


def _test_metrics(path: Path) -> dict:
    d = json.loads(path.read_text())["by_noise"]["all"]
    return {a: d[a]["metrics"] for a in ("zupt", "trapezoid")}


def write_mahony_calibrated(none_test: Path, mahony_test: Path, out: Path) -> None:
    nm = _test_metrics(none_test)
    mm = _test_metrics(mahony_test)
    rows = []
    for label, algo in (("ZUPT", "zupt"), ("Trapezoid", "trapezoid")):
        n, m = nm[algo], mm[algo]
        err = _b(_f(m["clean_median_abs_err"], 2), m["clean_median_abs_err"] < n["clean_median_abs_err"])
        ci = _b(_f(m["clean_median_ci"], 2), m["clean_median_ci"] < n["clean_median_ci"])
        wf = _b(_pct(m["clean_frac_within_1_5m"]), m["clean_frac_within_1_5m"] > n["clean_frac_within_1_5m"])
        rows.append(
            f"\\multirow{{2}}{{*}}{{{label}}} & none (baseline) & {n['n_clean']} & "
            f"{_pct(n['clean_coverage_90'])} & {_f(n['clean_median_abs_err'], 2)} & "
            f"{_f(n['clean_median_ci'], 2)} & {_pct(n['clean_frac_within_1_5m'])} \\\\"
        )
        rows.append(
            f"                      & \\textbf{{Mahony}} & {m['n_clean']} & "
            f"{_pct(m['clean_coverage_90'])} & {err} & {ci} & {wf} \\\\"
        )
    body = "\n\\midrule\n".join("\n".join(rows[i:i + 2]) for i in range(0, len(rows), 2))
    out.write_text(
        "% Auto-generated by scripts/reproduce_gyro_report_tables.py:\n"
        "% conformal calibration refit on TRAIN, scored on the held-out TEST split.\n"
        "\\resizebox{\\textwidth}{!}{%\n"
        "\\begin{tabular}{llrrrrr}\n\\toprule\n"
        "Algorithm & Reconstruction & $n_{\\rm clean}$ & Cov@90 (GT-clean) & "
        "$\\tilde{|e|}$ (m) & $\\tilde w$ (m) & $\\le 1.5$\\,m \\\\\n\\midrule\n"
        f"{body}\n"
        "\\bottomrule\n\\end{tabular}%\n}\n"
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--comparison", type=Path, required=True)
    ap.add_argument("--none-test", type=Path, required=True)
    ap.add_argument("--mahony-test", type=Path, required=True)
    ap.add_argument(
        "--out", type=Path,
        default=Path(__file__).resolve().parents[1] / "docs/latex/figures/gyro",
    )
    a = ap.parse_args(argv)
    a.out.mkdir(parents=True, exist_ok=True)

    comp = json.loads(a.comparison.read_text())
    write_pred_improvement(comp, a.out / "pred_improvement.tex")
    write_seg_improvement(comp, a.out / "seg_improvement.tex")
    write_mahony_calibrated(a.none_test, a.mahony_test, a.out / "mahony_calibrated.tex")
    print(f"wrote pred_improvement.tex, seg_improvement.tex, mahony_calibrated.tex -> {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
