#!/usr/bin/env python
"""Build a SELF-CONTAINED ``pyramidElevatorDist`` wheel by vendoring its ``src.*`` closure.

The tracked repo keeps ``src/`` as the single source of truth and the façade keeps its
``from src.`` imports. This script materializes a self-contained package in a staging
dir by:

  1. importing the façade and exercising every public entry point to discover the exact
     runtime closure of ``src.*`` modules (self-maintaining — no hardcoded list);
  2. copying the façade + that closure into ``build/pkg/pyramidElevatorDist/`` with the
     closure nested under a private ``_impl/`` subpackage;
  3. rewriting ``from src.`` -> ``from pyramidElevatorDist._impl.`` in every copied file;
  4. neutralizing the one import-time ``sys.path.insert`` landmine;
  5. running ``python -m build`` against the staged package -> ``dist/``;
  6. (unless ``--skip-smoke``) installing the wheel into a FRESH venv and asserting it
     imports and runs all 7 entry points with NO top-level ``src`` package present.

Run:  venv/bin/python packaging/build_wheel.py [--skip-smoke]
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PKG = "pyramidElevatorDist"
IMPL = "_impl"
STAGE = REPO / "build" / "pkg"
DIST = REPO / "dist"
WHEEL_TPL = REPO / "packaging" / "wheel"
SMOKE_VENV = REPO / "build" / "smoke-venv"
FACADE_FILES = ["__init__.py", "signal.py", "predection.py", "segmentor.py", "_orchestration.py"]


def log(msg: str) -> None:
    print(f"[build_wheel] {msg}", flush=True)


# --------------------------------------------------------------------------- #
# 1. Discover the runtime closure of src.* modules
# --------------------------------------------------------------------------- #
def compute_closure() -> dict[str, str | None]:
    """Import the façade, exercise all 7 public entry points, and collect every
    ``src.*`` module that ended up in ``sys.modules``. Returns {modname: file|None}
    (``None`` for a namespace package with no ``__init__.py``)."""
    sys.path.insert(0, str(REPO))
    import numpy as np
    import pandas as pd
    import pyramidElevatorDist as P

    fs, secs = 50, 120
    n = secs * fs
    t = (np.arange(n) / fs * 1000.0)
    z = np.full(n, 9.81)
    bump = np.hanning(15 * fs)
    z[30 * fs:45 * fs] += 0.6 * bump
    acc = pd.DataFrame({"timestamp_ms": t, "x": np.zeros(n), "y": np.zeros(n), "z": z})
    seg = {"type": "up", "start_s": 30.0, "end_s": 45.0}
    prs = pd.DataFrame({"timestamp_ms": t[:100], "pressure": 1013.0 - np.arange(100) * 0.001})

    entry_points = [
        ("findSegments", lambda: P.findSegments(acc, resample=False)),
        ("findSegmentsDetailed", lambda: P.findSegmentsDetailed(acc, resample=False)),
        ("findSegmentParameters", lambda: P.findSegmentParameters(acc, 30.0, 45.0, resample=False)),
        ("predictSegment", lambda: P.predictSegment(acc, seg, resample=False)),
        ("predictByParameters", lambda: P.predictByParameters(acc, seg, {"W": 3.0, "f": 0.5, "abs_A": 0.3}, resample=False)),
        ("reconstructedSignal", lambda: P.reconstructedSignal(acc, resample=False)),
        ("barometricAltitude", lambda: P.barometricAltitude(prs)),
    ]
    for name, fn in entry_points:
        try:
            fn()
        except Exception as exc:  # noqa: BLE001 - closure discovery only needs the imports
            log(f"  note: {name} raised ({type(exc).__name__}: {exc}) — imports still captured")

    closure = {
        name: getattr(mod, "__file__", None)
        for name, mod in list(sys.modules.items())
        if name == "src" or name.startswith("src.")
    }
    log(f"closure: {len(closure)} src.* modules")
    return closure


# --------------------------------------------------------------------------- #
# 2-5. Stage the self-contained package
# --------------------------------------------------------------------------- #
def stage_package(closure: dict[str, str | None]) -> None:
    if STAGE.exists():
        shutil.rmtree(STAGE)
    pkg_dst = STAGE / PKG
    impl_dst = pkg_dst / IMPL
    impl_dst.mkdir(parents=True)

    # -- façade --
    for fname in FACADE_FILES:
        shutil.copy2(REPO / PKG / fname, pkg_dst / fname)

    # -- _impl package marker (src/__init__.py is a bare comment; keep a clear header) --
    (impl_dst / "__init__.py").write_text(
        '"""Vendored implementation of pyramidElevatorDist.\n\n'
        "Generated by packaging/build_wheel.py from the repo's src/ tree — do not edit.\n"
        '"""\n'
    )

    # -- closure modules -> _impl/<subpath> --
    dir_map: dict[Path, Path] = {}  # source dir -> staged dir (for sibling *.json)
    for name in sorted(closure):
        if name == "src":
            continue  # the root maps to _impl/__init__.py (written above)
        file = closure[name]
        rel = Path(*name[len("src."):].split("."))
        if file and file.endswith("__init__.py"):
            dst = impl_dst / rel / "__init__.py"
        elif file:  # a plain module .py
            dst = impl_dst / rel.with_suffix(".py")
        else:  # namespace package (no __init__.py in src) -> create an empty one
            dst = impl_dst / rel / "__init__.py"
        dst.parent.mkdir(parents=True, exist_ok=True)
        if file:
            shutil.copy2(file, dst)
            dir_map[Path(file).parent] = dst.parent
        elif not dst.exists():
            dst.write_text("")

    # -- ensure every staged directory is a real package --
    for d in [impl_dst, *[p for p in impl_dst.rglob("*") if p.is_dir()]]:
        init = d / "__init__.py"
        if not init.exists():
            init.write_text("")

    # -- sibling *.json resources (config.json x2, calibration.json x2) --
    n_res = 0
    for src_dir, dst_dir in dir_map.items():
        for jf in src_dir.glob("*.json"):
            shutil.copy2(jf, dst_dir / jf.name)
            n_res += 1
    log(f"copied {n_res} JSON resource file(s)")

    # -- rewrite src.* imports across façade + _impl --
    n_rw = sum(rewrite_imports(p) for p in pkg_dst.rglob("*.py"))
    log(f"rewrote src.* imports in {n_rw} file(s)")

    # -- neutralize the import-time sys.path.insert landmine --
    neutralize_syspath(impl_dst)

    # -- staged build config (version injected from __version__) --
    version = read_version()
    (STAGE / "pyproject.toml").write_text(
        (WHEEL_TPL / "pyproject.toml").read_text().replace("__VERSION__", version)
    )
    shutil.copy2(WHEEL_TPL / "README.md", STAGE / "README.md")
    shutil.copy2(WHEEL_TPL / "MANIFEST.in", STAGE / "MANIFEST.in")
    log(f"staged pyramidElevatorDist {version} at {STAGE}")


def rewrite_imports(path: Path) -> int:
    """Rewrite `from src.` / `import src.` -> `... pyramidElevatorDist._impl. ...` on
    import lines only (leaves any incidental 'src' in strings/comments untouched).
    Returns 1 if the file changed, else 0."""
    lines = path.read_text().splitlines(keepends=True)
    changed = False
    out = []
    for line in lines:
        s = line.lstrip()
        new = line
        if s.startswith("from src.") or s.startswith("from src "):
            new = line.replace("from src", f"from {PKG}.{IMPL}", 1)
        elif s.startswith("import src."):
            new = line.replace("import src", f"import {PKG}.{IMPL}", 1)
        elif s.rstrip() == "import src" or s.startswith("import src "):
            new = line.replace("import src", f"import {PKG}.{IMPL} as src", 1)
        if new != line:
            changed = True
        out.append(new)
    if changed:
        path.write_text("".join(out))
    return 1 if changed else 0


def neutralize_syspath(impl_dst: Path) -> None:
    """Remove the import-time `sys.path.insert(0, _REPO_ROOT)` in the vendored
    fit_elevator_parameters/common.py — the vendored imports are absolute, so the
    repo-layout hack is both unnecessary and wrong inside a wheel."""
    common = (impl_dst / "segmentation" / "algorithms" / "accelerometer_only"
              / "template_match" / "fit_elevator_parameters" / "common.py")
    if not common.exists():
        log("WARNING: vendored common.py not found — sys.path landmine NOT neutralized")
        return
    text = common.read_text()
    block = (
        "if str(_REPO_ROOT) not in sys.path:\n"
        "    sys.path.insert(0, str(_REPO_ROOT))"
    )
    replacement = "pass  # vendored: repo-root sys.path insertion neutralized"
    if block in text:
        common.write_text(text.replace(block, replacement, 1))
        log("neutralized sys.path.insert in vendored common.py")
    else:
        log("WARNING: sys.path.insert block not found in common.py (already changed?)")


def read_version() -> str:
    text = (REPO / PKG / "__init__.py").read_text()
    m = re.search(r'__version__\s*=\s*["\']([^"\']+)["\']', text)
    if not m:
        raise SystemExit("could not find __version__ in pyramidElevatorDist/__init__.py")
    return m.group(1)


def build() -> Path:
    DIST.mkdir(exist_ok=True)
    subprocess.run([sys.executable, "-m", "build", "--wheel", str(STAGE),
                    "--outdir", str(DIST)], check=True)
    subprocess.run([sys.executable, "-m", "build", "--sdist", str(STAGE),
                    "--outdir", str(DIST)], check=True)
    # pip/setuptools normalizes the distribution name to lowercase in the filename.
    wheel = sorted(DIST.glob("*.whl"), key=lambda p: p.stat().st_mtime)[-1]
    log(f"built {wheel.name}")
    return wheel


# --------------------------------------------------------------------------- #
# 6. Clean-room smoke test (fresh venv, no repo on path)
# --------------------------------------------------------------------------- #
SMOKE_DRIVER = r'''
import importlib.util, sys
assert importlib.util.find_spec("src") is None, "FAIL: wheel leaked a top-level 'src' package"
import numpy as np, pandas as pd
import pyramidElevatorDist as P
fs, n = 50, 120*50
t = np.arange(n)/fs*1000.0
z = np.full(n, 9.81); z[30*fs:45*fs] += 0.6*np.hanning(15*fs)
acc = pd.DataFrame({"timestamp_ms": t, "x": np.zeros(n), "y": np.zeros(n), "z": z})
seg = {"type": "up", "start_s": 30.0, "end_s": 45.0}
prs = pd.DataFrame({"timestamp_ms": t[:100], "pressure": 1013.0 - np.arange(100)*0.001})
P.findSegments(acc, resample=False)
P.findSegmentsDetailed(acc, resample=False)
P.findSegmentParameters(acc, 30.0, 45.0, resample=False)
P.predictSegment(acc, seg, resample=False)
P.predictByParameters(acc, seg, {"W": 3.0, "f": 0.5, "abs_A": 0.3}, resample=False)
P.reconstructedSignal(acc, resample=False)
P.barometricAltitude(prs)
print(f"SMOKE OK: pyramidElevatorDist {P.__version__} at {P.__file__}")
'''


def smoke_test(wheel: Path) -> None:
    if SMOKE_VENV.exists():
        shutil.rmtree(SMOKE_VENV)
    log(f"creating fresh smoke venv at {SMOKE_VENV} …")
    subprocess.run([sys.executable, "-m", "venv", str(SMOKE_VENV)], check=True)
    py = SMOKE_VENV / "bin" / "python"
    subprocess.run([str(py), "-m", "pip", "install", "--quiet", "--upgrade", "pip"], check=True)
    log("installing wheel (+deps from index) into the fresh venv …")
    subprocess.run([str(py), "-m", "pip", "install", "--quiet", str(wheel)], check=True)
    # cwd = the smoke venv so the repo root (and its src/) is NOT on sys.path
    subprocess.run([str(py), "-c", SMOKE_DRIVER], check=True, cwd=str(SMOKE_VENV))
    log("clean-room smoke test PASSED")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-smoke", action="store_true",
                    help="build the wheel but skip the fresh-venv smoke test")
    args = ap.parse_args()

    closure = compute_closure()
    stage_package(closure)
    wheel = build()
    if args.skip_smoke:
        log("skipping smoke test (--skip-smoke)")
    else:
        smoke_test(wheel)
    log(f"done -> {DIST}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
